on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.91.0  # MSRV
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build (default features)
        run: cargo build --verbose --all
      - name: Build (no default features)
        run: cargo build --verbose --all --no-default-features

      - name: Build (debug feature)
        run: cargo build --verbose --all --no-default-features --features=debug
      - name: Build (delta feature)
        run: cargo build --verbose --all --no-default-features --features=delta
      - name: Build (get-size2 feature)
        run: cargo build --verbose --all --no-default-features --features=get-size2
      - name: Build (retain feature)
        run: cargo build --verbose --all --no-default-features --features=retain
      - name: Build (serde feature)
        run: cargo build --verbose --all --no-default-features --features=serde
      - name: Build (std feature)
        run: cargo build --verbose --all --no-default-features --features=std
      - name: Build (sync feature)
        run: cargo build --verbose --all --no-default-features --features=sync

      - name: Build (all features except sync)
        run: cargo build --verbose --all --no-default-features --features=debug,delta,get-size2,retain,serde,std
      - name: Build (all features)
        run: cargo build --verbose --all --all-features
